name: Publish changes (if version changed)

on:
  push:
    branches:
      - master

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      # Configurar el repositorio
      - uses: actions/checkout@v4

      # Configurar Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      # Instalar dependencias
      - run: npm i

      # Validar código
      - run: npm run format
      - run: npm run lint
      
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.npm_token }}
        run: npx semantic-release
 